### PR TITLE
Fix some integer and size issues

### PR DESCRIPTION
**Pull request by SeanBurford**
I have found some issues in UEFIExtract using American Fuzzy Lop (http://lcamtuf.coredump.cx/afl/) that are worth fixing.  There's a mix of out of bounds reads, infinite loops and I'm pretty sure there's an arbitrary write in FfsEngine::rebase

This patch addresses the crashes and loops AFL found.

### CODE REVIEW

**Comment by NikolajSchlej** [comment]
Thanks a lot, will apply the patch step by step to both master and new_engine branches and release a new versions of all tools.

**Comment by NikolajSchlej** [comment]
Applied fixes to master branch, reworked your patch a bit. 
Could you please retest it on the same set of input files?
UEFIExtract uses a different engine now, could you fuzz it too?
Thanks in advance.

**Comment by SeanBurford** [comment]
Running my samples against branch new_engine UEFIExtract I get one hang and one crash, so almost all issues are addressed.

The hang is near ffsparser.cpp:887 so I suspect that volumeSize is zero:
#0  0x00000000004b87c1 in TreeItem::header (this=0x708380) at ../common/treeitem.cpp:171
#1  0x00000000004c2156 in TreeModel::header (this=<optimized out>, index=...) at ../common/treemodel.cpp:154
#2  0x000000000047f7a5 in FfsParser::parseRawArea (this=this@entry=0x7fffffffdab0, data=..., index=...) at ../common/ffsparser.cpp:887
#3  0x00000000004a0ff2 in FfsParser::parseImageFile (this=this@entry=0x7fffffffdab0, buffer=..., root=...) at ../common/ffsparser.cpp:192
#4  0x0000000000404a88 in main (argc=2, argv=<optimized out>) at uefiextract_main.cpp:52
Indeed, volumeSize is zero:
(gdb) frame 2
#2  0x000000000047edc7 in FfsParser::parseRawArea (this=this@entry=0x7fffffffdab0, data=..., index=...) at ../common/ffsparser.cpp:902
902	        result = findNextVolume(index, data, volumeOffset + prevVolumeSize, volumeOffset);
(gdb) print volumeSize
$1 = 0

The crash is a segfault when peHeader->Signature is read, so dosHeader->e_lfanew is invalid:
FfsParser::parsePeImageSectionBody (this=this@entry=0x7fffffffdab0, index=...) at ../common/ffsparser.cpp:2451
2451	        if (peHeader->Signature != EFI_IMAGE_PE_SIGNATURE) {
Here's the backtrace for that one:
#0  FfsParser::parsePeImageSectionBody (this=this@entry=0x7fffffffdab0, index=...) at ../common/ffsparser.cpp:2451
#1  0x00000000004916eb in FfsParser::parseSectionBody (this=this@entry=0x7fffffffdab0, index=...) at ../common/ffsparser.cpp:2024
#2  0x00000000004781c3 in FfsParser::parseSections (this=this@entry=0x7fffffffdab0, sections=..., index=...) at ../common/ffsparser.cpp:1717
#3  0x000000000047954a in FfsParser::parseFileBody (this=this@entry=0x7fffffffdab0, index=...) at ../common/ffsparser.cpp:1592
#4  0x000000000047b7cf in FfsParser::parseVolumeBody (this=this@entry=0x7fffffffdab0, index=...) at ../common/ffsparser.cpp:1378
#5  0x00000000004809e1 in FfsParser::parseRawArea (this=this@entry=0x7fffffffdab0, data=..., index=...) at ../common/ffsparser.cpp:929
#6  0x00000000004a0ff2 in FfsParser::parseImageFile (this=this@entry=0x7fffffffdab0, buffer=..., root=...) at ../common/ffsparser.cpp:192
#7  0x0000000000404a88 in main (argc=2, argv=<optimized out>) at uefiextract_main.cpp:52
(gdb) p dosHeader->e_lfanew
$2 = 16777215

**Comment by NikolajSchlej** [comment]
Thanks a lot. 
I've fuzzed the new engine too a bit, and found some other crashes, so I decided to harden the parser by adding checks around pointer operations. All was well until I've found out, that parsing of GUID-defined sections part must be rewritten from scratch, which I will try to do next week.
Anyway, thank you for introducing me to AFL.

**Comment by SeanBurford** [comment]
Running my samples against branch master UEFIExtract I get one crash and one infinite loop.

The crash is due to recursion filling up the stack.  This is caused by parseSection calling parseSections with processed == section:
(gdb) frame 6
#6  0x0000000000493ba4 in FfsEngine::parseSection (this=this@entry=0x791220, 
    section=..., index=..., parent=..., mode=mode@entry=0 '\000')
    at ../ffsengine.cpp:1743
1743	            result = parseSections(processed, index);
(gdb) p processed
$2 = {d = 0x7ffff29ec010}
(gdb) p section
$3 = (const QByteArray &) @0x7fffff807120: {d = 0x7ffff29ec010}
Partial backtrace:
#2  0x0000000000493ba4 in FfsEngine::parseSection (this=this@entry=0x791220, 
    section=..., index=..., parent=..., mode=mode@entry=0 '\000')
    at ../ffsengine.cpp:1743
#3  0x00000000004a8d99 in FfsEngine::parseSections (this=this@entry=0x791220, 
    body=..., parent=...) at ../ffsengine.cpp:1409
#4  0x0000000000493ba4 in FfsEngine::parseSection (this=this@entry=0x791220, 
    section=..., index=..., parent=..., mode=mode@entry=0 '\000')
    at ../ffsengine.cpp:1743
#5  0x00000000004a8d99 in FfsEngine::parseSections (this=this@entry=0x791220, 
    body=..., parent=...) at ../ffsengine.cpp:1409

The infinite loop is something I've found since the pull request.  It seems to be caused by FfsEngine::findNextVolume finding an EFI_FV_SIGNATURE exactly EFI_FV_SIGNATURE_OFFSET bytes into a volume, which results in nextVolumeOffset == volumeOffset.

**Comment by SeanBurford** [comment]
Yeah, afl-fuzz is great.  

I find I have to fix up one reference to gcc and two references to g++ in Makefile after running qmake:
$ cd UEFITool/UEFIExtract/
$ export AFL_PATH=.../src/afl/afl-1.94b/
$ export CC=${AFL_PATH}/afl-gcc
$ export CXX=${AFL_PATH}/afl-g++
$ qmake uefiextract.pro
$ vi Makefile (fix up CC and CXX and LINK)
$ make

Also, if you have SSD drives it's a good idea to run it from tmpfs rather than thrashing your flash:
$ cd /tmp
$ mkdir fuzz
$ sudo mount -t tmpfs -o size=4096M -o uid=${USER} tmpfs /tmp/fuzz

**Comment by NikolajSchlej** [comment]
Thanks. 
UEFIExtract of master branch is not supported anymore, as it uses the old engine. I decided to not fix all the crashes in it, but rush for new_engine development to replace it ASAP.

**Pull request closed without merging**
