### PR TITLE
Fix align overflow 

### LINKED ISSUE #38: UEFIExtract folder names in OS X
Hi,

UEFIExtract will not use the GUID for firmware volumes for OS X EFI images. It instead uses "AppleCRC32 AppleFSO" text field that shows ip on UEFITool.

Instead of this code in FfsEngine::recursiveDump
QString childPath = QString("%1/%2 %3").arg(path).arg(i).arg(model->text(childIndex).isEmpty() ? model->name(childIndex) : model->text(childIndex));
it probably should be
QString childPath = QString("%1/%2 %3").arg(path).arg(i).arg(model->name(childIndex));

Personally I find it more useful to have the GUID as folder name instead of that text.

Best,
fG!

### LINKED ISSUE #144: UEFIExtract NE A51 замечания (продолжение к #136)
Всем доброго здравия!
UEFIExtract NE A51 с момента релиза накопилось несколько нюансов которые хотелось бы прояснить.
Тестовый файл биоса https://cloud.mail.ru/public/64Lc/8vuiN6yVU

1) опция '-о имя папки'
    Например распаковываем файл PE32 IRST в папку Test
    uefiextract ROG-RAMPAGE-VI-EXTREME-ASUS-1401.CAP 91B4D9C1-141C-4824-8D02-3C298E36EB3F -o test -m body -t 10
    В результате в папке test видим файл body.bin и errorlevel по выполнению 0.
    Теперь сделаем "ошибку" в -t
    uefiextract ROG-RAMPAGE-VI-EXTREME-ASUS-1401.CAP 91B4D9C1-141C-4824-8D02-3C298E36EB3F -o test -m body -t 18
    В результате получаем пустую папку test и ! errorlevel 0 !, что не есть правильно. По логике если не найдено хоть что то папка не должна быть создана и левел не должен быть 0.

2) опция '-m file'
    К примеру извлечем все FFS-RAW микодов
    uefiextract ROG-RAMPAGE-VI-EXTREME-ASUS-1401.CAP 17088572-377F-44EF-8F4E-B09FFF46A070 -o test -m file
    Всё хорошо и замечательно все 3 файла как есть, но в биосе есть и дркгие файлы собранные как FFS RAW и вот с ними проблема, например в этом же биосе OROM VBIOS. Извлекаем:
    uefiextract ROG-RAMPAGE-VI-EXTREME-ASUS-1401.CAP B981F167-9D2B-4CA0-82E9-63DF0E3C3BF3 -o test -m file
    В папке test получаем file.ffs, но размер явно не htader+OROM, те 65 кило а целый DXE том.

Спасибо. :)

### LINKED ISSUE #149: Support GZip compression
For example found in SD835 (OnePlus 5) image.

See https://twitter.com/zhuowei/status/1057710243465969664

### LINKED ISSUE #152: UEFIExtract producing duplicates of extracted files
Версии отображаются, тут всё нормально, просто когда начинаем очередные сборки тестить, то путаница иногда возникает какой файл был какой есть и тп.
Как я сказал это не критично. При следующмх тестах будц просто по пкпкам раскилывать, так оно проще будет.

Кстати плодёж файлов не совсем убрался. Вот выловил сегодня.
https://cloud.mail.ru/public/64Lc/8vuiN6yVU
`uefiextract bios.bin DE3E049C-A218-4891-8658-5FC0FA84C788 -o test - m file`
в бивисе с такмс GUID файл 1, но на выходе 3 FFS, как обычно по количеству секций

_Originally posted by @LSSoniX in https://github.com/LongSoft/UEFITool/issues/145#issuecomment-439678362_

### LINKED ISSUE #163: nvram file guid
#define NVRAM_AMI_NVAR_STORE_FILE_GUID         "{77D3DC50-D42B-4916-AC80-8F469035D150}"
not processing in A54
example:
https://drive.google.com/file/d/1ZU6sv0gqWWqV1ysYAHWHZR9JbvTtA9O3/view

### LINKED ISSUE #215: [NE] ME FPT parser: false "invalid checksum" message when ROM Bypass present and not Empty(0x00)
I have no patch yet.

### LINKED ISSUE #246: Freeze upon loading Intel Tatlow images
UEFITool seems to (usually) freeze when trying to load [Intel Tatlow (RKL-E)](https://ark.intel.com/content/www/us/en/ark/products/series/213678/intel-c250-series-chipsets.html) SPI images. Sample links below:

https://www.supermicro.com/Bios/softfiles/14259/BIOS_X12STD-F-1C31_20210831_1.0_STDsp.zip
https://dlcdnets.asus.com/pub/ASUS/server/P12R-M/BIOS/P12R-M-ASUS-0211.zip
https://dlcdnets.asus.com/pub/ASUS/server/P12R-E_Series/BIOS&FW/P12R-E-ASUS-0301.zip

The latest commits do generate a lot of warnings when compiling but I believe this freeze was happening before as well.

```
UEFITool-new_engine\common\nvramparser.cpp: In member function 'USTATUS NvramParser::parseNvarStore(const QModelIndex&)':
UEFITool-new_engine\common\nvramparser.cpp:350:72: warning: unknown conversion type character 'l' in format [-Wformat=]
                 info += usprintf("\nTimestamp: %" PRIX64 "h", timestamp);
                                                                        ^
UEFITool-new_engine\common\nvramparser.cpp:350:72: warning: too many arguments for format [-Wformat-extra-args]
UEFITool-new_engine\common\nvramparser.cpp: In member function 'USTATUS NvramParser::findNextStore(const QModelIndex&, const QByteArray&, UINT32, UINT32, UINT32&)':
UEFITool-new_engine\common\nvramparser.cpp:632:195: warning: unknown conversion type character 'l' in format [-Wformat=]
                     msg(usprintf("%s: FTW block candidate at offset %Xh skipped, has invalid body size %llXh", __FUNCTION__, localOffset + offset, (unsigned long long)ftw64Header->WriteQueueSize), index);
                                                                                                                                                                                                   ^
UEFITool-new_engine\common\nvramparser.cpp:632:195: warning: too many arguments for format [-Wformat-extra-args]
UEFITool-new_engine\common\nvramparser.cpp: In member function 'USTATUS NvramParser::parseVssStoreBody(const QModelIndex&, UINT8)':
UEFITool-new_engine\common\nvramparser.cpp:1538:96: warning: unknown conversion type character 'l' in format [-Wformat=]
             info += usprintf("\nMonotonic counter: %" PRIX64 "h\nTimestamp: ", monotonicCounter) + efiTimeToUString(timestamp)
                                                                                                ^
UEFITool-new_engine\common\nvramparser.cpp:1538:96: warning: too many arguments for format [-Wformat-extra-args]
UEFITool-new_engine\common\nvramparser.cpp: In member function 'USTATUS NvramParser::parseFlashMapBody(const QModelIndex&)':
UEFITool-new_engine\common\nvramparser.cpp:1928:36: warning: unknown conversion type character 'l' in format [-Wformat=]
                 entryHeader->Offset);
                                    ^
UEFITool-new_engine\common\nvramparser.cpp:1928:36: warning: format '%X' expects argument of type 'unsigned int', but argument 4 has type 'UINT64 {aka long long unsigned int}' [-Wformat=]
UEFITool-new_engine\common\nvramparser.cpp:1928:36: warning: too many arguments for format [-Wformat-extra-args]
UEFITool-new_engine\common\meparser.cpp: In member function 'USTATUS MeParser::parseFptRegion(const QByteArray&, const QModelIndex&, QModelIndex&)':
UEFITool-new_engine\common\meparser.cpp:180:38: warning: format '%lX' expects argument of type 'long unsigned int', but argument 2 has type 'unsigned int' [-Wformat=]
                         ptEntry->Type);
                                      ^
UEFITool-new_engine\common\meparser.cpp:180:38: warning: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'unsigned int' [-Wformat=]
UEFITool-new_engine\common\meparser.cpp: In member function 'USTATUS MeParser::parseIfwi16Region(const QByteArray&, const QModelIndex&, QModelIndex&)':
UEFITool-new_engine\common\meparser.cpp:336:69: warning: unknown conversion type character 'l' in format [-Wformat=]
                             (unsigned long long)ifwiHeader->Checksum);
                                                                     ^
UEFITool-new_engine\common\meparser.cpp:336:69: warning: too many arguments for format [-Wformat-extra-args]
UEFITool-new_engine\common\utility.cpp: In function 'QString errorCodeToUString(USTATUS)':
UEFITool-new_engine\common\utility.cpp:187:93: warning: format '%lX' expects argument of type 'long unsigned int', but argument 2 has type 'USTATUS {aka unsigned int}' [-Wformat=]
     default:                                return usprintf("Unknown error %02lX", errorCode);
                                                                                             ^
UEFITool-new_engine\common\ffsparser.cpp: In member function 'USTATUS FfsParser::parsePeImageSectionBody(const QModelIndex&)':
UEFITool-new_engine\common\ffsparser.cpp:3167:42: warning: unknown conversion type character 'l' in format [-Wformat=]
             optionalHeader.H64->ImageBase);
                                          ^
UEFITool-new_engine\common\ffsparser.cpp:3167:42: warning: too many arguments for format [-Wformat-extra-args]
UEFITool-new_engine\common\ffsparser.cpp: In member function 'USTATUS FfsParser::parseTeImageSectionBody(const QModelIndex&)':
UEFITool-new_engine\common\ffsparser.cpp:3209:87: warning: unknown conversion type character 'l' in format [-Wformat=]
             teHeader->ImageBase + teHeader->StrippedSize - sizeof(EFI_IMAGE_TE_HEADER));
                                                                                       ^
UEFITool-new_engine\common\ffsparser.cpp:3209:87: warning: unknown conversion type character 'l' in format [-Wformat=]
UEFITool-new_engine\common\ffsparser.cpp:3209:87: warning: too many arguments for format [-Wformat-extra-args]
UEFITool-new_engine\common\ffsparser.cpp: In member function 'USTATUS FfsParser::addInfoRecursive(const QModelIndex&)':
UEFITool-new_engine\common\ffsparser.cpp:3377:115: warning: unknown conversion type character 'l' in format [-Wformat=]
                 model->addInfo(index, usprintf("Data address: %08llXh\n", (unsigned long long)address + headerSize),false);
                                                                                                                   ^
UEFITool-new_engine\common\ffsparser.cpp:3377:115: warning: too many arguments for format [-Wformat-extra-args]
UEFITool-new_engine\common\ffsparser.cpp:3378:104: warning: unknown conversion type character 'l' in format [-Wformat=]
                 model->addInfo(index, usprintf("Header address: %08llXh\n", (unsigned long long)address), false);
                                                                                                        ^
UEFITool-new_engine\common\ffsparser.cpp:3378:104: warning: too many arguments for format [-Wformat-extra-args]
UEFITool-new_engine\common\ffsparser.cpp:3381:97: warning: unknown conversion type character 'l' in format [-Wformat=]
                 model->addInfo(index, usprintf("Address: %08llXh\n", (unsigned long long)address), false);
                                                                                                 ^
UEFITool-new_engine\common\ffsparser.cpp:3381:97: warning: too many arguments for format [-Wformat-extra-args]
UEFITool-new_engine\common\ffsparser.cpp: In member function 'USTATUS FfsParser::parseFit(const QModelIndex&)':
UEFITool-new_engine\common\ffsparser.cpp:3862:83: warning: unknown conversion type character 'l' in format [-Wformat=]
         currentStrings.push_back(usprintf("%016" PRIX64 "h", currentEntry->Address));
                                                                                   ^
UEFITool-new_engine\common\ffsparser.cpp:3862:83: warning: too many arguments for format [-Wformat-extra-args]
UEFITool-new_engine\common\ffsparser.cpp: In member function 'USTATUS FfsParser::parseFitEntryAcm(const QByteArray&, UINT32, const QModelIndex&, QString&, UINT32&)':
UEFITool-new_engine\common\ffsparser.cpp:4013:25: warning: format '%lX' expects argument of type 'long unsigned int', but argument 5 has type 'unsigned int' [-Wformat=]
                         );
                         ^
UEFITool-new_engine\common\ffsparser.cpp:4013:25: warning: format '%lX' expects argument of type 'long unsigned int', but argument 13 has type 'unsigned int' [-Wformat=]
UEFITool-new_engine\common\ffsparser.cpp:4013:25: warning: format '%lX' expects argument of type 'long unsigned int', but argument 21 has type 'unsigned int' [-Wformat=]
UEFITool-new_engine\common\ffsparser.cpp:4013:25: warning: format '%lX' expects argument of type 'long unsigned int', but argument 22 has type 'unsigned int' [-Wformat=]
UEFITool-new_engine\common\ffsparser.cpp: In member function 'USTATUS FfsParser::parseFitEntryBootGuardBootPolicy(const QByteArray&, UINT32, const QModelIndex&, QString&, UINT32&)':
UEFITool-new_engine\common\ffsparser.cpp:4208:39: warning: unknown conversion type character 'l' in format [-Wformat=]
                                       );
                                       ^
UEFITool-new_engine\common\ffsparser.cpp:4208:39: warning: unknown conversion type character 'l' in format [-Wformat=]
UEFITool-new_engine\common\ffsparser.cpp:4208:39: warning: format '%X' expects argument of type 'unsigned int', but argument 6 has type 'UINT64 {aka long long unsigned int}' [-Wformat=]
UEFITool-new_engine\common\ffsparser.cpp:4208:39: warning: format '%X' expects argument of type 'unsigned int', but argument 7 has type 'UINT64 {aka long long unsigned int}' [-Wformat=]
UEFITool-new_engine\common\ffsparser.cpp:4208:39: warning: too many arguments for format [-Wformat-extra-args]
UEFITool-new_engine\common\ffsparser.cpp: In member function 'USTATUS FfsParser::parseBpdtRegion(const QByteArray&, UINT32, UINT32, const QModelIndex&, QModelIndex&)':
UEFITool-new_engine\common\ffsparser.cpp:4562:38: warning: format '%lX' expects argument of type 'long unsigned int', but argument 2 has type 'unsigned int' [-Wformat=]
                         ptEntry->Size) +
                                      ^
UEFITool-new_engine\common\ffsparser.cpp:4562:38: warning: format '%lu' expects argument of type 'long unsigned int', but argument 3 has type 'unsigned int' [-Wformat=]
UEFITool-new_engine\common\ffsparser.cpp: In member function 'USTATUS FfsParser::parseCpdRegion(const QByteArray&, UINT32, const QModelIndex&, QModelIndex&)':
UEFITool-new_engine\common\ffsparser.cpp:5015:134: warning: format '%lX' expects argument of type 'long unsigned int', but argument 3 has type 'unsigned int' [-Wformat=]
                                          manifestHeader->ExponentSize * sizeof(UINT32), manifestHeader->ExponentSize * sizeof(UINT32));
                                                                                                                                      ^
UEFITool-new_engine\common\ffsparser.cpp:5015:134: warning: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'unsigned int' [-Wformat=]
UEFITool-new_engine\common\ffsparser.cpp:5015:134: warning: format '%lX' expects argument of type 'long unsigned int', but argument 9 has type 'unsigned int' [-Wformat=]
UEFITool-new_engine\common\ffsparser.cpp:5015:134: warning: format '%lu' expects argument of type 'long unsigned int', but argument 10 has type 'unsigned int' [-Wformat=]
UEFITool-new_engine\common\ffsparser.cpp:5015:134: warning: format '%lX' expects argument of type 'long unsigned int', but argument 16 has type 'unsigned int' [-Wformat=]
UEFITool-new_engine\common\ffsparser.cpp:5015:134: warning: format '%lu' expects argument of type 'long unsigned int', but argument 17 has type 'unsigned int' [-Wformat=]
UEFITool-new_engine\common\ffsparser.cpp:5015:134: warning: format '%lX' expects argument of type 'long unsigned int', but argument 18 has type 'unsigned int' [-Wformat=]
UEFITool-new_engine\common\ffsparser.cpp:5015:134: warning: format '%lu' expects argument of type 'long unsigned int', but argument 19 has type 'unsigned int' [-Wformat=]
UEFITool-new_engine\common\ffsparser.cpp: In member function 'USTATUS FfsParser::parseCpdExtensionsArea(const QModelIndex&)':
UEFITool-new_engine\common\ffsparser.cpp:5176:173: warning: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'unsigned int' [-Wformat=]
                     msg(usprintf("%s: IFWI Partition Manifest hash size is %d, expected %lu", __FUNCTION__, attrHeader->HashSize, sizeof (attrHeader->CompletePartitionHash)), extIndex);
                                                                                                                                                                             ^
UEFITool-new_engine\common\ffsparser.cpp:5202:143: warning: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'unsigned int' [-Wformat=]
                     msg(usprintf("%s: Module Attributes hash size is %d, expected %lu", __FUNCTION__, hashSize, sizeof (attrHeader->ImageHash)), extIndex);
                                                                                                                                               ^
UEFITool-new_engine\common\ffsparser.cpp: In member function 'USTATUS FfsParser::parseSignedPackageInfoData(const QModelIndex&)':
UEFITool-new_engine\common\ffsparser.cpp:5253:164: warning: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'unsigned int' [-Wformat=]
                 msg(usprintf("%s: CPD Signed Package Info hash size is %d, expected %lu", __FUNCTION__, moduleHeader->HashSize, sizeof (moduleHeader->MetadataHash)), extIndex);
```

### PR DESCRIPTION
**Pull request by slavonnet**
Need review. I think must be more condotons

### CODE REVIEW

**Comment by slavonnet** [comment]
This ,maximum about alig what i was  fund

https://manualzz.com/doc/12085895/intel-platform-innovation-framework-for-efi-firmware-file...#p23

**Comment by slavonnet** [comment]
Before fix tool say : fss align 10h greater than vilume. But fss align can't be more 7 and on debug i se Zero or x40 in attrs. Rewrite to remove any overflow

**Comment by NikolajSchlej** [comment]
We will not accept any pull-requests without first getting a good understanding of the reason for modification, an agreement of the need for modification, and the technical details of it. 

Please provide more context to your fixes in a separate issue:
- what is the nature of the issue
- is there an image that has this issue reproducible
- if so, how we can reproduce it
- what is the difference between expected and observed behaviors
- what is the way to test that the modification actually fixes the issue and doesn't introduce any new ones

I will leave this PR without action until the questions above are answered and me and @vit9696 are in agreement on the solution.

**Comment by NikolajSchlej** [comment]
"Before fix tool say : fss align 10h greater than volume"
This is a legitimate error message coming from the following paragraph in the UEFI PE specification:
volume_alignment

The error message you see indicates that there's a file in that volume that required 16 byte alignment, but the volume itself was aligned by a lower boundary, most likely 8. 

However, there's still an issue in UEFITool because the EFI_FVB2_WEAK_ALIGNMENT handling is not performed yet, and such volumes will be reported as improperly aligned despite not being so. This will be fixed, but the PR here needs to be closed unmerged.

**Pull request closed without merging**
