### PR TITLE
Display message when search fails

### PR DESCRIPTION
**Pull request by druckdev**
Display a message 'could not be found' when the UEFITool search fails.

### CODE REVIEW

**Comment by druckdev** [comment]
I was quite unsure on how to best format some of the long lines. Please do tell me if there is a Coding Style Guide or similar.

**Comment by NikolajSchlej** [comment]
There is no defined coding style, format as you see fit.

This design is somewhat strange though, as it exposes the msg() function of ffsFinder for unclear reason. UEFITool class should not care about messages generated by ffsFinder, it just relays them to Search panel.

**Comment by druckdev** [comment]
I agree!

Could you please take a look at the new commit? If you don't like the wrapper function we could leave the old ones and just check at the end if `(ret != U_SUCCESS && index == mode->index(0,0))` but that seems less efficient.

**Comment by druckdev** [comment]
(Renamed index back to rootIndex in the wrapper functions)

**Comment by NikolajSchlej** [comment]
Wrappers are just fine, LGTM.

**Pull request merged**
