### PR TITLE
Informational: Pull request ball with updates by forks

### PR DESCRIPTION
**Pull request by timofonic**
Hello.

I-m not sure what-s the current status of UEFITool. I'm not sure what happebs with the "new engine" branch and when it will be merged to master.

Meanwhile, I collected everything I was able to with a fork. My coding skills are awful, so I relied on automatically mergeable code.

Do whatever you want to do with it. I'm sure it's a mess, but it's nice to know it from others. Also, I want to know what's going in UEFITool, I'm a Linux user and 99.999999% tools for UEFI/BIOS/firmware stuff are Windows-only (flashrom doesn't support my system, for example).

My system (MSI GE62 2QD Apache Pro) has an Opti V AMI BIOS, the ACPI is awful and I want to improve the BIOS in many ways (it has some subtle errors) but the EC chip is a PITA too and that would require 8051 dissasembler (it uses the same ENE Technology chip used in OLPC). I can betatest whatever thing, despite I'm new in this area too :)

Thanks for all your hard work, people!

Kind regards.

### CODE REVIEW

**Comment by timofonic** [comment]
@LongSoft What do you think?

**Comment by skochinsky** [comment]
Nikolaj no longer maintaining this project. 
In any case, this PR is way too massive IMO to be even considered for reviewing, let alone merging. Nobody wants to sift through hundreds of changes with vague descriptions to figure out what's good and what's fluff (ROG theme, really?).
I'm not really sure if there's anything here that can be taken without loads of work...

**Comment by NikolajSchlej** [comment]
I'm indeed not able to maintain this project anymore, but Igor is right: most of those changes aren't really needed in the mainline, because they are either cosmetics or out of scope.
I'm well aware of TuxUser's fork called OzmTool, because I helped developing it back then, and even linked it in the new README file.
Moreover, master branch is abandoned and no one really plans to develop it further, all development is done in new_engine branch for the last 2 years.

**Comment by timofonic** [comment]
@skochinsky @NikolajSchlej Thanks a lot for your replies!

I knew the PR is too massive and has many "crap" on it, sorry if I didn't explain it well enough. I just wanted to show my really insignificant effort (by using automated merging), so maybe it could inspire other more skilled people to do something better. I may try to merge more stuff, but my attempts at merge conflict resolving are a total disaster (the same happened wih ACPICA stuff, I broke IASL in my branch!).

To @NikolajSchlej , @skochinsky and the rest of UEFITool related people: What about passing the torch to others and make a call for volunteers in places where there would be more interested people ([win-raid](https://www.win-raid.com) and other bios modding sites, techie sites, etc)? I'm sure there would be people interested on this, specially after the latest Intel ME news and such :)

I think companies like @system76 would be interested in this tool too. Maybe even others!

**Pull request closed without merging**
